### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by feijianli** [ispamm/PHBreast#5]
When I was training the patch classifier, I ran into a problem. In the phc_model.py file, the local variable 'out_6' referenced before assignment

**Comment by elelo22** [comment]
Hi, thank you for reporting the issue. I fixed the problem, it should work now :)

**Comment by feijianli** [comment]
Hi, thank you for your reply. Can you share your pytorchtools.EarlyStopping file? I found that the one I downloaded from the internet is not the same as yours.

**Comment by elelo22** [comment]
What do you mean share? It's already in the repository under early-stopping-pytorch/pytorchtools.py

**Comment by feijianli** [comment]
I'm sorry, I didn't notice your update of this file. Thank you for sharing!
