### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by feijianli** [ispamm/PHBreast#6]
hello，Can you share your Inbreast dataset? I downloaded the dataset from the internet and the patient Id was removed, making it impossible to make a dataset file.

**Comment by elelo22** [comment]
Hi, I also have the version with the patient id removed in the INbreast.csv file. However, their README file says:
`The filename includes an anonymized patient ID.  For instance, in the filename ‘20586908_6c613a14b80a8591_MG_R_CC_ANON’, ‘6c613a14b80a8591’ is the patient ID that can be used to aggregate DICOMs in cases and to link dicoms with the medical report.`

So , you can use this to make the dataset, you can find the code to do that [here](https://github.com/ispamm/PHBreast/blob/main/utils/Preprocessing_INbreast.ipynb).
