### ISSUE TITLE
packages' version

### ISSUE THREAD

**Issue by 18370636086** [ispamm/PHBreast#8]
hello, your requirment.txt say is torch==1.10.0 and torchvision==0.11.2, but the two packages' version is conflict, could your give more correct package version under your environment? Thank you very much!

**Comment by elelo22** [comment]
Hi, I am not sure why that is, but I just checked and in the environment I have those versions (torch 1.10.1 and torchvision 0.11.2).

**Comment by 18370636086** [comment]
oh, i know, your requirment.txt write is torch==1.10.0 , i guess it should be torch==1.10.1. Thank for your timely reply!

**Comment by elelo22** [comment]
no problem, thanks for letting me know :)
